#!/usr/bin/env bash

source .environment

curl https://raw.githubusercontent.com/RadicalZephyr/attache/master/install.sh | sh

RET=$?

if [ $RET -ne 0 ]
then
    echo "Install script exited with status: $RET."
    exit 1
fi

if [ -d $HOME/.attache ]
then
    echo ".attache directory not found."
    exit 1
fi

exit 0
