#!/usr/bin/env bash

fixtures=$(ls link/.fixtures 2> /dev/null)

for fixture in $fixtures
do
    echo link/$fixture
    cat >link/$fixture <<EOF
#!/usr/bin/env bash
./.link $fixture
EOF
    chmod +x link/$fixture
done > .clean-tests
