#!/usr/bin/env bash

source ../.environment

$HERMIT_ROOT/bin/hermit init

FILE=.testfile

touch $HOME/$FILE

$HERMIT_ROOT/bin/hermit add $HOME/$FILE

$HERMIT_ROOT/bin/hermit link
$HERMIT_ROOT/bin/hermit unlink
