#!/usr/bin/env bash

source ../.environment

hermit init $TEST_PROFILE_NAME

DIR="$(hermit git rev-parse --show-toplevel | tail -n 1)"

if [ "$DIR" = $HERMIT_ROOT/$PROFILE_DIR_NAME/$TEST_PROFILE_NAME ]; then
  exit 0
else
  exit 1
fi
