#!/usr/bin/env bash

source ../.install-environment

# Run the install test with a different install location
export INSTALL_DIR="$HOME/.foo/.bar/.baz/.adifferentplace"
export HERMIT_DIR=$INSTALL_DIR

exec ./.do-install
