#!/usr/bin/env bash

source ../.environment

# Run the install test with a different install location
export INSTALL_DIR="$HOME/.foo/.bar/.baz/.adifferentplace"
export ATTACHE_DIR=$INSTALL_DIR

exec ./.do-install
