#!/usr/bin/env bash

source ../.environment

pushd $HOME/.hermit

git checkout $(git describe HEAD --abbrev=0)~1

popd

$HOME/.hermit/bin/hermit upgrade

RET=$?

cd $HOME/.hermit

if git describe HEAD --exact-match; then
    :
else
    echo "Failed to checkout an exact release tag"
    exit 1
fi

exit $RET
