#!/usr/bin/env bash

source ../.environment

$HERMIT_ROOT/bin/hermit init $TEST_PROFILE_NAME

DIR=the-test-dir

mkdir -p $HOME/$DIR

echo things and stuff > $HOME/$DIR/foo
echo other stuff ands > $HOME/$DIR/bar
echo and stuff things > $HOME/$DIR/baz
echo and things stuff > $HOME/$DIR/qux

$HERMIT_ROOT/bin/hermit add $HOME/$DIR

RET=$?

if [ \! -d $HERMIT_ROOT/$PROFILE_DIR_NAME/$TEST_PROFILE_NAME/$DIR ]
then
    echo "There is no directory $DIR inside the profile."
    exit 1
fi

for file in foo bar baz qux
do

    if [ \! -f $HERMIT_ROOT/$PROFILE_DIR_NAME/$TEST_PROFILE_NAME/$DIR/$file ]
    then
        echo "$file is not present inside $DIR in the profile."
        exit 1
    fi

done

exit $RET
