#!/usr/bin/env bash

source ../.environment

$HERMIT_ROOT/bin/hermit init $TEST_PROFILE_NAME

FILE=.testfile

cat > $HOME/$FILE <<EOF
"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
minim veniam, quis nostrud exercitation ullamco laboris nisi ut
aliquip ex ea commodo consequat. Duis aute irure dolor in
reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum."
EOF

$HERMIT_ROOT/bin/hermit add $HOME/$FILE

RET=$?

if [ \! -f $HERMIT_ROOT/$PROFILE_DIR_NAME/$TEST_PROFILE_NAME/$FILE ]
then
    echo "There is no actual file $FILE in the profile."
    exit 1
fi


if [ \! -L $HOME/$FILE ]
then
    echo "There is no symbolic link at $HOME/$FILE."
    exit 1
fi

exit $RET
