#!/usr/bin/env bash

source ../.environment

$HOME/.hermit/bin/hermit init $TEST_PROFILE_NAME

FILE=.testfile
ln -s nowhere $HOME/$FILE

$HOME/.hermit/bin/hermit add $HOME/$FILE

RET=$?

if [ -f $HOME/.hermit/profiles/$TEST_PROFILE_NAME/$FILE ]
then
    echo "The symlink was erroneously added to the profile."
    exit 1
fi

exit $RET
