#!/usr/bin/env bash

source ../.environment

hermit init $TEST_PROFILE_NAME

FILE=.testfile
ln -s nowhere $HOME/$FILE

hermit add $HOME/$FILE

RET=$?

if [ -f $HERMIT_ROOT/$PROFILE_DIR_NAME/$TEST_PROFILE_NAME/$FILE ]
then
    echo "The symlink was erroneously added to the profile."
    exit 1
fi

exit $RET
