#!/usr/bin/env bash


# Copyright 2014, Geoff Shannon

# This file is part of Attaché.

# Attaché is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Attaché is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Attaché. If not, see <http://www.gnu.org/licenses/>.

set -e
[ -n "$ATTACHE_DEBUG" ] && set -x

shopt -s dotglob
files=$(echo $ATTACHE_ROOT/*)
shopt -u dotglob

for file in $files
do
    # ATTACHE_ROOT is an absolute path, so strip to just the base filename
    basefile=$(basename $file)

    if [ -h $HOME/$basefile ]
    then
        echo "There is already a symbolic link at $HOME/$basefile"
        echo "Maybe you've already linked it?"
        continue

    elif [ -f $HOME/$basefile ]
    then
        echo "There's a real file at $HOME/$basefile!"
        echo "We can't create a link there."
        continue

    elif [ -d $HOME/$basefile ]
    then
        echo "There's a real directory at $HOME/$basefile."
        continue
    fi

    # Lots of other cases here, could be all sorts of other files
    if [ \! -h $HOME/$basefile ]
    then
        ln -s $file $HOME/$basefile
    fi

done
