#!/usr/bin/env bash

# Copied shamelessly from rbenv, copyright Sam Stephenson
# See LICENSE.rbenv for details

set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export ATTACHE_DEBUG=1
  shift
fi

if [ -n "$ATTACHE_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "attache: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${ATTACHE_ROOT}" ]; then
  ATTACHE_ROOT="${HOME}/.attache"
else
  ATTACHE_ROOT="${ATTACHE_ROOT%/}"
fi
export ATTACHE_ROOT

if [ -z "${ATTACHE_DIR}" ]; then
  ATTACHE_DIR="$(pwd)"
else
  cd "$ATTACHE_DIR" 2>/dev/null || {
    echo "attache: cannot change working directory to \`$ATTACHE_DIR'"
    exit 1
  } >&2
  ATTACHE_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export ATTACHE_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${ATTACHE_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

hook_path="${ATTACHE_HOOK_PATH}:${ATTACHE_ROOT}/attache.d:/usr/local/etc/attache.d:/etc/attache.d:/usr/lib/attache/hooks"
for plugin_hook in "${ATTACHE_ROOT}/plugins/"*/etc/attache.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export ATTACHE_HOOK_PATH="$hook_path"

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(attache---version)\n$(attache-help)" >&2
  ;;
"-v" )
  exec attache---version
  ;;
* )
  command_path="$(command -v "attache-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "attache: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
