#!/usr/bin/env bash
#
# Summary: Display the version of attache
#
# Displays the version number of this attache release, including the
# current revision from git, if available.
#
# The format of the git revision is:
#   <version>-<num_commits>-<git_sha>
# where `num_commits` is the number of commits since `version` was
# tagged.

# Copied shamelessly from rbenv, copyright Sam Stephenson
# See LICENSE.rbenv for details

set -e
[ -n "$ATTACHE_DEBUG" ] && set -x

version="0.1.0"

if cd "$ATTACHE_ROOT" 2>/dev/null; then
  git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
  git_revision="${git_revision#v}"
fi

echo "Attaché ${git_revision:-$version}"
