#!/usr/bin/env bash
# Usage: attache completions <command> [arg1 arg2...]

# Copied shamelessly from rbenv, copyright Sam Stephenson
# See LICENSE.rbenv for details

set -e
[ -n "$ATTACHE_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  attache-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "attache-$COMMAND" || command -v "attache-sh-$COMMAND")"
if grep -iE "^([#%]|--|//) provide attache completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
