#!/usr/bin/env bash

# Copied shamelessly from rbenv, copyright Sam Stephenson
# See LICENSE.rbenv for details

set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export ATTACHE_DEBUG=1
  shift
fi

if [ -n "$ATTACHE_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

# Make sure git is installed
GIT=$(type -p git | head -1)
if [ -z "$GIT" ]; then
    echo "Attache relies heavily on git for it's functionality."
    echo
    echo "Please install git before attempting to use Attache."
    exit 1
fi

# Make sure that git commands won't fail because user isn't configured
if git config --global user.name > /dev/null &&
   git config --global user.email > /dev/null
then
    :
else
    echo -e 'Please set your git name and email with:\n
  git config --global user.name "Your Name"
  git config --global user.email "you@example.com"'
    echo
    exit 1
fi

export READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "attache: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${ATTACHE_ROOT}" ]; then
  ATTACHE_ROOT="${HOME}/.attache"
else
  ATTACHE_ROOT="${ATTACHE_ROOT%/}"
fi
export ATTACHE_ROOT

if [ -z "${ATTACHE_PROFILE}" ]; then
  ATTACHE_PROFILE="${ATTACHE_ROOT}/profiles/default"
fi
export ATTACHE_PROFILE

if [ -z "${SECRETS_SUFFIX}" ]; then
  SECRETS_SUFFIX=".attache_secrets"
fi
export SECRETS_SUFFIX

shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${ATTACHE_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

# Currently, we don't actually do anything with hooks. We may want to
# support them in the future though, so keep this code hunk.

# hook_path="${ATTACHE_HOOK_PATH}:${ATTACHE_ROOT}/attache.d:/usr/local/etc/attache.d:/etc/attache.d:/usr/lib/attache/hooks"
# for plugin_hook in "${ATTACHE_ROOT}/plugins/"*/etc/attache.d; do
#   hook_path="${hook_path}:${plugin_hook}"
# done
# export ATTACHE_HOOK_PATH="$hook_path"

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(attache---version)\n$(attache-help)" >&2
  ;;
"-v" )
  exec attache---version
  ;;
* )
  command_path="$(command -v "attache-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "attache: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
