#!/usr/bin/env bash


# Copyright 2014, Geoff Shannon

# This file is part of Attaché.

# Attaché is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Attaché is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Attaché. If not, see <http://www.gnu.org/licenses/>.

set -e
[ -n "$ATTACHE_DEBUG" ] && set -x

shopt -s dotglob
files=$(echo $ATTACHE_ROOT/*)
shopt -u dotglob

for file in $files
do
    # ATTACHE_ROOT is an absolute path, so strip to just the base
    # filename and replace concatenated with HOME
    basefile=$HOME/$(basename $file)

    if [ -h $basefile ]
    then
        if [ "$($READLINK $basefile)" = "$file" ]
        then
            echo "$(basename $file) is already linked!"
        else
            echo "There is already a symbolic link at $basefile"
            echo "But it doesn't point to $file."
        fi
        continue

    elif [ -f $basefile ]
    then
        echo "There's a real file at $basefile!"
        echo "We can't create a link there."
        continue

    elif [ -d $basefile ]
    then
        echo "There's a real directory at $basefile."
        continue
    fi

    # Lots of other cases here, could be all sorts of other files
    if [ \! -h $basefile ]
    then
        ln -s $file $basefile
    fi

done
