#!/usr/bin/env bash
#
# Summary: Start a new attaché profile
# Usage: attache init [profile-name]

# Copyright Geoff Shannon, 2014

# This file is part of Attaché.

# Attaché is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Attaché is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Attaché. If not, see <http://www.gnu.org/licenses/>.

set -e
[ -n "$ATTACHE_DEBUG" ] && set -x

[ -d $ATTACHE_DIR ] && echo "The folder $ATTACHE_DIR already exists!
Maybe you should change your ATTACHE_DIR environment variable..." && exit 1

mkdir -p $ATTACHE_DIR

pushd $ATTACHE_DIR >/dev/null 2>/dev/null

git init
echo "*$SECRETS_SUFFIX" > .gitignore
git add .gitignore
git commit -m "Initial commit"

popd >/dev/null 2>/dev/null

echo "Congratulations! You now have a brand new attache located at $ATTACHE_DIR"
