#!/usr/bin/env bash
#
# Summary: Start a new attaché profile
# Usage: attache init [profile-name]

# Copyright 2014, Geoff Shannon

# This file is part of Attaché.

# Attaché is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Attaché is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Attaché. If not, see <http://www.gnu.org/licenses/>.

set -e
[ -n "$ATTACHE_DEBUG" ] && set -x

# Check for extraneous arguments and exit with an error if they exist.
if [ ! $# -le 1 ]
then
    echo "Error: attache: Too many arguments."
    attache help init && exit 1
fi

# Change profile name from default if optional argument is given.
[ -n "$1" ] && ATTACHE_PROFILE="${ATTACHE_ROOT}/profiles/${1}"

[ -d $ATTACHE_PROFILE ] && echo "The directory $ATTACHE_PROFILE already exists!
Maybe you should change your ATTACHE_PROFILE environment variable..." && exit 1

mkdir -p $ATTACHE_PROFILE

pushd $ATTACHE_PROFILE >/dev/null 2>/dev/null

git init
echo "*${SECRETS_SUFFIX}" > .gitignore
git add .gitignore
git commit -m "Initial commit"

popd >/dev/null 2>/dev/null

echo "Congratulations! You now have a brand new attache located at $ATTACHE_PROFILE."
