#!/usr/bin/env bash

# Copyright 2014, Geoff Shannon

# This file is part of Hermit.

# Hermit is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Hermit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Hermit. If not, see <http://www.gnu.org/licenses/>.

# Make sure that git commands won't fail because user isn't configured
if git config --global user.name  > /dev/null &&
   git config --global user.email > /dev/null
then
    :
else
    echo -e 'Please set your git name and email with:\n
  git config --global user.name "Your Name"
  git config --global user.email "you@example.com"'
    echo
    exit 1
fi
