#!/usr/bin/env bash
#
# Summary: Add files to your hermit
# Usage: hermit add [<filepattern>…]

# Copyright 2014, Geoff Shannon

# This file is part of Hermit.

# Hermit is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Hermit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Hermit. If not, see <http://www.gnu.org/licenses/>.

set -e
[ -n "$HERMIT_DEBUG" ] && set -x

for file in $@; do
    origfile=$file
    newfile=$HERMIT_PROFILE/${origfile#~/}

    if [ -f $newfile ]
    then
        echo "${origfile#~/} is already in your hermit!"
        exit 1
    fi

    mkdir -vp $(dirname $newfile)
    echo "mv: $(mv -vn $origfile $newfile)"
    echo "ln: $(ln -vs $newfile $origfile)"
done
