#!/usr/bin/env bash
#
# Summary: Add files to your hermit directory
# Usage: hermit add [<filepattern>…]
#
# Add takes a path (or paths) to some files and directories in your
# home folder, and moves them into your active hermit profile, and
# then creates a symlink to this moved file in the original location.
#
# Adding a directory is essentially a shorthand for adding all files
# in that directory tree.
#
#  Note: you must have an initialized hermit profile.

# Copyright 2014, Geoff Shannon

# This file is part of Hermit.

# Hermit is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Hermit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Hermit. If not, see <http://www.gnu.org/licenses/>.

set -e
[ -n "$HERMIT_DEBUG" ] && set -x

check-git-config
check-hermit-profile

for file in $@
do

    if [ -d $file ]
    then
        file=$(find $file -type d -name .git -prune -o -type f)
    fi

    for origfile in $file
    do
        newfile=$HERMIT_PROFILE_PATH/${origfile#~/}

        if [ -f $newfile ]
        then
            echo "${origfile#~/} is already in your hermit!"
            exit 1
        fi

        mkdir -vp $(dirname $newfile)
        echo "mv: $(mv -vn $origfile $newfile)"
        echo "ln: $(ln -vs $newfile $origfile)"
    done
done
