#!/usr/bin/env bash


# Copyright 2014, Geoff Shannon

# This file is part of Hermit.

# Hermit is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Hermit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Hermit. If not, see <http://www.gnu.org/licenses/>.

set -e
[ -n "$HERMIT_DEBUG" ] && set -x

source $(dirname $0)/utilities

# Provide hermit completions
if [ "$1" = "--complete" ]; then
    hermit_print_profiles

    exit
fi

check_hermit_profile

#Find all files in current profile
find "$HERMIT_PROFILE_PATH" -type d -name .git -prune -o -type f -print |
while read file_path
do
    #Strip profile prefix then prepend home directory
    relative_path=~/${file_path#$HERMIT_PROFILE_PATH/}

    #Make sure relative_path is a symbolic link before delete
    test -L $relative_path && rm $relative_path
done

exit 0
