#!/usr/bin/env bash
#
# Summary: Switch to using a different profile
#
# Usage: hermit use [profile-name]


# Copyright 2014, Geoff Shannon

# This file is part of Hermit.

# Hermit is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Hermit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Hermit. If not, see <http://www.gnu.org/licenses/>.

set -e
[ -n "$HERMIT_DEBUG" ] && set -x

source $(dirname $0)/utilities

# Provide hermit completions
if [ "$1" = "--complete" ]; then
    hermit_print_profiles

    exit
fi

check_hermit_profile

TO_PROFILE="$1"

# First check if the name given is a directory under
# $HERMIT_ROOT/profiles.
if [ \! -d "$HERMIT_ROOT/profiles/$TO_PROFILE" ]; then
    echo "$TO_PROFILE is not a valid hermit profile."
    exit 1
fi

# Now, unlink all files from the currently active profile (hermit unlink)

# We use || true because hermit-unlink fails sometimes, possibly
# related to using the idiom '| while read'
hermit unlink || true

# Set the $HERMIT_CURRENT_KEY to the new profile
set_current_profile $TO_PROFILE

# Link all the files for the current profile (hermit link)
hermit link

echo "You are now using profile $TO_PROFILE."
