#!/usr/bin/env bash


# Copyright 2014, Geoff Shannon

# This file is part of Hermit.

# Hermit is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Hermit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Hermit. If not, see <http://www.gnu.org/licenses/>.

set -e
[ -n "$HERMIT_DEBUG" ] && set -x

echo "hermit-use - NOT IMPLEMENTED"

# First check if the name given is a directory under
# $HERMIT_ROOT/profiles.

# Now, unlink all files from the currently active profile (hermit unlink)

# Set the $HERMIT_CURRENT_KEY to the new profile

# Link all the files for the current profile (hermit link)
