#!/usr/bin/env bash
#
# Summary: Create a local hermit from an existing remote hermit
# Usage: hermit fetch <repository> [profile-name]

# Copyright 2014, Geoff Shannon

# This file is part of Hermit.

# Hermit is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Hermit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Hermit. If not, see <http://www.gnu.org/licenses/>.

set -e
[ -n "$HERMIT_DEBUG" ] && set -x

# Make sure we have at least one argument
if [ ! $# -ge 1 ]
then
    echo "Error: hermit: Too few arguments."
    hermit help fetch && exit 1
fi

FETCH_URL="$1"

# Make sure we don't have more than 2 arguments
if [ ! $# -le 2 ]
then
    echo "Error: hermit: Too many arguments."
    hermit help fetch && exit 1
fi

# Change profile name from default if optional argument is given
[ -n "$2" ] && HERMIT_PROFILE="${HERMIT_ROOT}/profiles/${2}"

[ -d $HERMIT_PROFILE ] && echo "The folder $HERMIT_PROFILE already exists!
Maybe you should change your HERMIT_PROFILE environment variable..." && exit 1

git clone $FETCH_URL $HERMIT_PROFILE

set_hermit_profile $HERMIT_PROFILE

echo "Successfully fetched remote profile into $HERMIT_PROFILE."
