#!/usr/bin/env bash
#
# Summary: Make sure your hermit setup is sane
#
# Usage: hermit doctor


# Copyright 2014, Geoff Shannon

# This file is part of Hermit.

# Hermit is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Hermit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Hermit. If not, see <http://www.gnu.org/licenses/>.

set -e
[ -n "$HERMIT_DEBUG" ] && set -x

# Provide hermit completions
if [ "$1" = "--complete" ]; then
   exit
fi

echo "Sanity checking your Hermit config..."
echo

if [ -d "$HERMIT_ROOT" ]; then
    :
else
    :
    exit 1
fi

if [ -d "$HERMIT_PROFILE_PATH" ]; then
    :
else
    :
fi

for profile_dir in "$HERMIT_ROOT/profiles/*"
do
    if [ -d "$profile_dir" ]; then
        ignore_file="$profile_dir/.gitignore"
        if [ -f "$ignore_file" ]; then
           if grep -E '\*.hermit_(secrets|complete)' profiles/default/.gitignore > /dev/null 2>&1; then
               : # properly ignored
           else
               : # missing ignores in profile
           fi
        fi
    else
        echo "Non-directory file" \
             "${profile_dir#$HERMIT_ROOT/profiles/}"
        echo "found in profiles directory."
    fi

done

# Do printing of profiles missing ignores here
