#!/usr/bin/env bash
#
# Summary: Upgrade gets you the latest released version of hermit
# Usage: hermit upgrade

# Copyright 2015, Geoff Shannon

# This file is part of Hermit.

# Hermit is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Hermit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Hermit. If not, see <http://www.gnu.org/licenses/>.

set -e
[ -n "$HERMIT_DEBUG" ] && set -x

if [ "$1" = "--complete" ]; then
    exit
fi

cd "$HERMIT_ROOT"

# Get a remote name we can use, defaulting to origin
if git remote | grep origin >/dev/null 2>&1; then
    remote=origin
else
    remote=$(git remote | head -n1)
fi

# Ensure that we can fetch all refs from this remote
old_fetch=$(git config remote.${remote}.fetch)
git config remote.${remote}.fetch "+refs/heads/*:refs/remotes/${remote}/*"

# Specifically fetch master from our chosen remote
git fetch $remote master

# Update to the bleeding edge
git checkout $remote/master >/dev/null 2>&1

# Revert to the latest release
git checkout $(git describe HEAD --abbrev=0) >/dev/null 2>&1

#restore old fetch settings
git config remote.${remote}.fetch "$old_fetch"

echo "You are now using hermit:" $(git describe HEAD --exact-match)
