#!/usr/bin/env bash
#
# Summary: Display the status of your hermit
# Usage: hermit status

# Copyright 2014, Geoff Shannon

# This file is part of Hermit.

# Hermit is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Hermit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Hermit. If not, see <http://www.gnu.org/licenses/>.

set -e
[ -n "$HERMIT_DEBUG" ] && set -x

if [ "$1" = "--complete" ]; then
    exit
fi

source $(dirname $0)/utilities

check_hermit_profile

echo "Hermit status:"
echo "Using profile $HERMIT_PROFILE"
echo "Located at: $HERMIT_PROFILE_PATH"
echo

pushd $HERMIT_PROFILE_PATH >/dev/null 2>/dev/null

redacted_files=$(find "$HERMIT_PROFILE_PATH" -type d -name .git -prune -o -type f -name '*.'${COMPLETE_SUFFIX} -print)

for file in $redacted_files
do
    redactfile="${file%.${COMPLETE_SUFFIX}}"

    if git diff --quiet "$redactfile"; then
        remove_verbosely "$redactfile"

        copy_verbosely "$completefile" "$redactfile"

        # Rev. patch the redact file.  This preserves
        # changes, but removes known secrets.
        patch -R "$redactfile" "$secretfile"

    else
        echo >&2 "hermit: Changes were made to $redactfile"
        echo >&2 "        Please only make changes to $completefile"
        echo >&2
    fi

done

echo "Git status:"
git status

popd >/dev/null 2>/dev/null
