#!/usr/bin/env bash
#
# Summary: Create a local hermit from an existing remote hermit
# Usage: hermit fetch <repository> [profile-name]

# Copyright 2014, Geoff Shannon

# This file is part of Hermit.

# Hermit is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Hermit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Hermit. If not, see <http://www.gnu.org/licenses/>.

set -e
[ -n "$HERMIT_DEBUG" ] && set -x

[ $# -lt 1 ] || echo "Not enough arguments!" && exit 1

[ -d $HERMIT_PROFILE ] && echo "The folder $HERMIT_PROFILE already exists!
Maybe you should change your HERMIT_PROFILE environment variable..." && exit 1

git clone $1 $HERMIT_PROFILE
