#!/usr/bin/env bash
#
# Summary: Redact files already stored in git
# Usage: hermit update [<filepattern>...]
#
# Update takes a path (or paths) to some files or directories in your
# home folder. For all the files that are already being tracked by
# Hermit, you are given the opportunity to redact the file.  The
# semantics of the redaction are the same as when passing a -r option
# to hermit add.
#
# It should be pointed out that attempting to redact information that
# has already been committed to the git repository is TOTALLY
# INEFFECTIVE.

# Copyright 2014, Geoff Shannon

# This file is part of Hermit.

# Hermit is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Hermit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Hermit. If not, see <http://www.gnu.org/licenses/>.

set -e
[ -n "$HERMIT_DEBUG" ] && set -x

check-git-config
check-hermit-profile

source $(dirname $0)/utilities


for file in $@
do

    file="$(absolute_path "$file")"

    file="$(files_when_dir "$file")"

    for origfile in $file
    do

        if [ -L "$origfile" ]
        then

            newfile="$(hermit_relative_path "$origfile")"
            link_target=$($READLINK "$origfile")

            if [ "$link_target" != "$newfile" ]
            then
                echo >&2 "hermit: This symlink is not handled by hermit: $origfile"
                echo >&2
                continue
            fi

            completefile="${newfile}.complete"
            redactfile="${newfile}"
            secretfile="${newfile}.${SECRETS_SUFFIX}"

            if [ -f "$completefile" -a -f "$redactfile" -a -f "$secretfile" ]
            then
                echo "Do a secondary redaction"
            else
                hermit_do_redaction "$completefile" "$redactfile" "$secretfile"
            fi

            echo

        elif [ -f "$origfile" ]
        then
            echo >&2 "hermit: update only works on files already tracked by hermit."
            echo >&2 "$origfile can be added to hermit with 'hermit add $origfile'"
            echo >&2

        fi

    done
done
