#!/usr/bin/env bash


# Copyright 2014, Geoff Shannon

# This file is part of Hermit.

# Hermit is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Hermit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Hermit. If not, see <http://www.gnu.org/licenses/>.

set -e
[ -n "$HERMIT_DEBUG" ] && set -x


#Find all files in current profile
find $HERMIT_PROFILE/ |
{
while read file_path; 
do
    #Find out what the symbolic link of each file in profile is.
    sym_link=~/${file_path#$HERMIT_PROFILE/}
    
    #Make sure sym_link is a symbolic link
    if [ $(readlink $sym_link) ]
    then
	rm $sym_link
    fi
done
}
