#!/usr/bin/env bash
#
# Summary: Make sure your hermit setup is sane
#
# Usage: hermit doctor


# Copyright 2014, Geoff Shannon

# This file is part of Hermit.

# Hermit is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Hermit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Hermit. If not, see <http://www.gnu.org/licenses/>.

set -e
[ -n "$HERMIT_DEBUG" ] && set -x

# Provide hermit completions
if [ "$1" = "--complete" ]; then
   exit
fi

echo "Sanity checking your Hermit config..."
echo

if [ -n "$HERMIT_ROOT" -a -d "$HERMIT_ROOT" ]; then
    :
else
    echo "Your HERMIT_ROOT environment variable is set incorrectly."
    echo "$HERMIT_ROOT is not an existing directory."
    exit 1
fi

if pushd "$HERMIT_ROOT" >/dev/null 2>&1; then
    if git describe --exact-match >/dev/null 2>&1; then
        echo "You're using a released version of hermit."
        git describe --exact-match
        echo
    else
        echo "You're using a bleeding edge hermit!"
        echo "I hope you know what you're doing\!"
        echo
    fi

    popd >/dev/null 2>&1
fi

if [ -n "$HERMIT_PROFILE_PATH" ]; then
    if [ -d "$HERMIT_PROFILE_PATH" ]; then
        :
    else
        echo "Your hermit profile directory does not exist!"
        echo "This is okay if you deleted it manually."
        echo

    fi
else
    echo "Something is wrong. HERMIT_PROFILE_PATH is unset or blank."
    echo
fi

needs_ignore_message() {
    echo "Please add '*.hermit_secrets' and '*.hermit_complete'."
    echo
}

for profile_dir in "$HERMIT_ROOT/profiles/*"
do
    if [ -d "$profile_dir" ]; then
        ignore_file="$profile_dir/.gitignore"
        if [ -f "$ignore_file" ]; then
           if grep -E '\*.hermit_(secrets|complete)' profiles/default/.gitignore > /dev/null 2>&1; then
               : # properly ignored
           else
               echo -n "The hermit profile $(basename $1)"
               echo " does not properly ignore hermit special files."
               echo
               needs_ignore_message "$profile_dir"
           fi
        else
            echo -n "The hermit profile $(basename $1)"
            echo " has no .gitignore and does not properly ignore"
            echo "hermit special files."
            echo
            needs_ignore_message "$profile_dir"
        fi
    else
        echo "Non-directory file" \
             "${profile_dir#$HERMIT_ROOT/profiles/}"
        echo "found in profiles directory."
    fi

done
