#!/usr/bin/env bash

source ../.environment

$HERMIT_ROOT/bin/hermit init

FILE=.testfile

touch $HOME/$FILE

$HERMIT_ROOT/bin/hermit add $HOME/$FILE

$HERMIT_ROOT/bin/hermit link # This is wrong. The flow should *not*
                              # be that you init, add, and then need
                              # to explicitly link your profile
$HERMIT_ROOT/bin/hermit use default
